name: GitHub Classroom Workflow

on: push

permissions:
  checks: write
  issues: write
  actions: read
  contents: read

jobs:
  grading:
    if: ${{ !contains(github.actor, 'classroom') }}
    uses: ./grading.yml
    with:
      MOODLE: true  # CHANGE true=export grade to moodle
    secrets: inherit
