name: GitHub Classroom autograding and update moodle

on:
  workflow_call:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grading:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student repo
        uses: actions/checkout@v4
        
      - name: Python test
        id: python-test
        uses: graphics80/autograding-python-grader@v1
        with:
          timeout: '15'
          max-score: '100'
          setup-command: 'pip install -r requirements.txt'

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          PYTHON-TEST_RESULTS: "${{steps.python-test.outputs.result}}"
        with:
          runners: python-test
